Repository seL4/camkes-tool, pull requests merged in 2021-09, with the labels that each got.

#88 CAmkES hardware tests + deployment
  .github/workflows/camkes-deploy.yml
  .github/workflows/test.yml
Labels: CI

#90 parser: fix attribute_reference regex
  camkes/parser/camkes.g
Labels: bug

#91 github: style check on diff only for this repo
  .github/workflows/push.yml
Labels: CI

#79 RISC-V: Support DTBs with one interrupt value per cell
  CHANGES
  camkes/templates/arch_helpers.py
  camkes/templates/dtb-query-common.template.c
  camkes/templates/macros.py
  camkes/templates/seL4DTBHardware-to.template.c
Labels: enhancement
